# These are supported funding model platforms

github: ColleagueRiley
# patreon: # Replace with a single Patreon username (not yet supported)
# ko_fi: # Replace with a single Ko-fi username (not yet supported)
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username (not yet supported)
