name: Build WebAssembly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v14

    - name: Build doxygen docs
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
          working-directory: './'
          doxyfile-path: './Doxyfile'
            
    - name: Compile to WebAssembly
      run: |
        make debug CC=emcc
        mv html docs
        
    - name: Deploy Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
